name: "CI"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "windows-latest"

    steps:
      - uses: actions/checkout@v2.3.4

      - name: "Build & test"
        run: |
          npm install
          npm run make
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith('${{ github.event.commits[0].message }}''v')
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: "${{ github.event.commits[0].message }}"
          prerelease: false
          title: "${{ github.event.commits[0].message }}"
          files: |
            dist/*.exe
            dist/*.blockmap
            dist/latest.yml