name: "CI"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "windows-latest"

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Dump GitHub context
        run: echo "$GITHUB_CONTEXT['event']['commits']['message']"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: "Build & test"
        run: |
          echo ${{github.event}}
          npm install
          npm run make
          npm run postpublish
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: $GITHUB_CONTEXT.event.commits.message
          prerelease: false
          title: $GITHUB_CONTEXT.event.commits.message
          files: |
            dist/*.exe
            dist/*.blockmap
            dist/latest.yml
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}