name: "CI"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "windows-latest"

    steps:
      - uses: actions/checkout@v2.3.4

      - name: "Build & test"
        run: |
          echo ${{ toJson(github.event.commits) }}
          echo ${{ github.event.commits.message }}
          echo ${{ toJson(github.event.commits[0].message) }}
          echo ${{ github.event.commits[0].message }}
          npm install
          npm run make
          npm run postpublish
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: ${{ toJson(github.event.commits.message)}}
          prerelease: false
          title: ${{ toJson(github.event.commits.message)}}
          files: |
            dist/*.exe
            dist/*.blockmap
            dist/latest.yml