name: "CI"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "windows-latest"

    steps:
      - uses: actions/checkout@v2.3.4
      - name: "Build & test"
        run: |
          npm install
          npm run make
          npm run postpublish
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: ${{ github }}
          prerelease: false
          title: ${{ steps.tag.outputs.result }}
          files: |
            dist/*.exe
            dist/*.blockmap
            dist/latest.yml