name: "CI"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "windows-latest"

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        if: runner.os != 'Windows'
      - name: Show GitHub ref
        run: echo "$GITHUB_REF"
        if: runner.os != 'Windows'
      - name: Dump event JSON
        env:
          EVENT_JSON_FILENAME: ${{ github.event_path }}
        run: cat "$EVENT_JSON_FILENAME"
        if: runner.os != 'Windows'

      - name: "Build & test"
        run: |
          npm install
          npm run make
          npm run postpublish
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: ${{ steps.vars.outputs.tag }}
          prerelease: false
          title: ${{ steps.vars.outputs.tag }}
          files: |
            dist/*.exe
            dist/*.blockmap
            dist/latest.yml